// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


final firestoreAppId=dotenv.env['firestoreAppId'];


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmofzHMrZIngQE91JZobYl-ZSU2fdjLXE',
    appId: '1:962439382171:android:a2356726dd6fd6cc7f723e',
    messagingSenderId: '962439382171',
    projectId: '$firestoreAppId',
    storageBucket: '$firestoreAppId.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrjAhQpGNib4Upcc6hztxK6XP_-XZWe9M',
    appId: '1:962439382171:ios:54a57860e611d1697f723e',
    messagingSenderId: '962439382171',
    projectId: '$firestoreAppId',
    storageBucket: '$firestoreAppId.firebasestorage.app',
    androidClientId: '962439382171-ndfr43g8hmakoio4co9ktup3lc59c6fc.apps.googleusercontent.com',
    iosClientId: '962439382171-le4qruugiu7b6q3v8kcu7q4119m5ksu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ssChat',
  );

}